### ISSUE TITLE
Provide changelog as output in GitHub action

### ISSUE THREAD

**Issue by timoknapp** [go-semantic-release/action#11]
Hi @christophwitzko ,

first of all I really like your work and appreciate that you started the go-based implementation of semantic-release! 
While playing around with your GitHub action, I struggled extracting the generated changelog information on runtime of the action it self. It seems that you only expose the new version as an output of the action. ([Set action output](https://github.com/go-semantic-release/action/blob/master/src/index.js#L70))

Could you maybe extend this output to also expose the changelog string. I would prefer this convenience, in order to directly reuse those info for following steps in my workflow. Would be great to use such an output like this:

```
...
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-file: package.json
      - name: Reuse Changelog
         run: echo Changelog: ${{ steps.semrel.outputs.changelog }} 
         if: steps.semrel.outputs.changelog != ''
```
