### ISSUE TITLE
dry breaks action

### ISSUE THREAD

**Issue by hazcod** [go-semantic-release/action#15]
Hi, providing `dry: true` breaks the action.

```yaml
name: Release Image

on:
  push:
    branches: [master]

jobs:

  release-image:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v2
    - 
      uses: go-semantic-release/action@v1
      id: version
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry: true
```

Logs:
```
Run go-semantic-release/action@v1
6
downloading semantic-release@^2.5.0
7
running semantic-release...
8
/home/runner/work/_temp/6c08cd1a-e776-4ead-b74c-7aa1b3e645e1 --version-file --changelog .generated-go-semantic-release-changelog.md --token *** --dry
9
[go-semantic-release]: version: 2.13.0
10
[go-semantic-release]: ci-condition plugin: GitHub Actions@1.2.1
11
[go-semantic-release]: provider plugin: GitHub@1.4.1
12
[go-semantic-release]: getting default branch...
13
[go-semantic-release]: found default branch: master
14
[go-semantic-release]: repo is private
15
[go-semantic-release]: found current branch: master
16
[go-semantic-release]: found current sha: 62608f29d773c7b54284d3ff14c0dd1d7516f56b
17
[go-semantic-release]: running CI condition...
18
[go-semantic-release]: getting latest release...
19
[go-semantic-release]: found version: 1.1.7
20
[go-semantic-release]: getting commits...
21
[go-semantic-release]: analyzing commits...
22
[go-semantic-release]: commit-analyzer plugin: default@1.3.1
23
[go-semantic-release]: calculating new version...
24
[go-semantic-release]: new version: 1.1.8
25
[go-semantic-release]: generating changelog...
26
[go-semantic-release]: changelog-generator plugin: default@1.5.0
27
[go-semantic-release]: DRY RUN: no release was created
28
Error: ENOENT: no such file or directory, open '.version'
```
