### ISSUE TITLE
Outdated Releases

### ISSUE THREAD

**Issue by bruuuuuuuce** [go-semantic-release/action#21]
I have a use case where I need to run a github job manually, push to main, and then cut a new release. My workflow looks like this
```
name: Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Backup Preprod Dashboards
        run: ./scripts/save_preprod_dashboards.sh
        env:
          PREPROD_BEARER_TOKEN: ${{ secrets.PREPROD_BEARER_TOKEN }}

      - name: Commit To Main
        run: |
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          git config --global user.name 'lab'
          git config --global user.email 'lab@lab.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "chore: backing up latest dashboards ${DATE}"
          git push
          sleep 10
        shell: bash

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          
      - name: Fetch Latest Commit
        run: |
          git fetch
          git pull origin main
          git pull --no-rebase --no-tags
          ls dashboards
          
      - name: Set release
        id: semrel
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
          force-bump-patch-version: true
```

I can see in the release step, when I `ls dashboards`, that I have the latest dashboards. However, when the release gets made, and I look at the tarball that is created, it seems to be 1 commit behind. So its using the commit sha that triggers the release vs using the latest from main, even though I am pulling latest with `git pull --no-rebase --no-tags`.
