### ISSUE TITLE
Configuration - .semrelrc

### ISSUE THREAD

**Issue by grzesuav** [go-semantic-release/action#26]
Hi,

how to load the setting from `.semrelrc` file ? Is it done automatically ? 

Second question regarding `change-log`, I have following setting
```yaml
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          changelog-file: "CHANGELOG.md"
```
however file `CHANGELOG.MD` is not getting updated, what is the proper configuration ?
