### ISSUE TITLE
Pass flags to hooks

### ISSUE THREAD

**Issue by ayashjorden** [go-semantic-release/action#35]
Hello,
It was easy to setup this action on my project, however, I have a new requirement to move the `.goreleaser.yaml` file under the `.github` folder.

I've gone through the source code of `goreleaser`, `go-semantic-release/semantic-release`, and its respective action, and I can't figure out how to pass the `goreleaser` flag `-f path/to/.goreleaser.yaml` from this action to the `goreleaser` hook.
From a different angle, I couldn't find the environment-variable that corresponds to the above in `goreleasr` own repo`.

```yml
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - uses: go-semantic-release/action@v1
        with:
          hooks: goreleaser <== How do I pass the `-f /path/to/.goreleaser.yaml` here?
          changelog-file: CHANGELOG.md
          allow-initial-development-versions: true
          prepend: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GORELEASER_CONFIG: <=== "this does not work as goreleaser does not bind on environment variables."
```

Thank you,
Jordan
